# PPRL TOOLKIT NOTEBOOK TUTORIAL 2026

## How to install PPRL Toolkit

In [1]:
%pip install "numpy<2"
%pip install -e .

Requirement already satisfied: numpy<2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.
Obtaining file:///home/lefteris/pprl_toolkit
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: dill in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (0.4.1)
Requirement already satisfied: flask in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (3.1.3)
Requirement already satisfied: numpy in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (1.26.4)
Requirement already satisfied: pandas==2.0.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (2.0.2)
Requirement already satisfied: python-dotenv in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (1.2.2)
Requirement already satisfied: requests==2.30.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (2.30.0)
Requirement already satisfied: metaphone in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (0.6)
Requirement already satisfied: cryptography in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (46.0.5)
Requirement already satisfied: google-cloud-storage in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (3.9.0)
Requirement already satisfied: google-cloud-logging in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (3.14.0)
Requirement already satisfied: google-cloud-kms in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (3.11.0)
Requirement already satisfied: scipy in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (1.17.1)
Requirement already satisfied: recordlinkage in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pprl==0.1.0) (0.16)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pandas==2.0.2->pprl==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pandas==2.0.2->pprl==0.1.0) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from pandas==2.0.2->pprl==0.1.0) (2025.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from requests==2.30.0->pprl==0.1.0) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from requests==2.30.0->pprl==0.1.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from requests==2.30.0->pprl==0.1.0) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from requests==2.30.0->pprl==0.1.0) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas==2.0.2->pprl==0.1.0) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from cryptography->pprl==0.1.0) (2.0.0)
Requirement already satisfied: pycparser in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography->pprl==0.1.0) (3.0)
Requirement already satisfied: blinker>=1.9.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from flask->pprl==0.1.0) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from flask->pprl==0.1.0) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from flask->pprl==0.1.0) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from flask->pprl==0.1.0) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from flask->pprl==0.1.0) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from flask->pprl==0.1.0) (3.1.6)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-kms->pprl==0.1.0) (2.30.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-kms->pprl==0.1.0) (2.49.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-kms->pprl==0.1.0) (1.78.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-kms->pprl==0.1.0) (1.27.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-kms->pprl==0.1.0) (6.33.5)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-kms->pprl==0.1.0) (0.14.3)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-kms->pprl==0.1.0) (1.73.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-kms->pprl==0.1.0) (1.78.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-kms->pprl==0.1.0) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-kms->pprl==0.1.0) (4.9.1)
Requirement already satisfied: typing-extensions~=4.12 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from grpcio<2.0.0,>=1.33.2->google-cloud-kms->pprl==0.1.0) (4.15.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-kms->pprl==0.1.0) (0.6.2)
Requirement already satisfied: google-cloud-appengine-logging<2.0.0,>=0.1.3 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-logging->pprl==0.1.0) (1.8.0)
Requirement already satisfied: google-cloud-audit-log<1.0.0,>=0.3.1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-logging->pprl==0.1.0) (0.4.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.0.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-logging->pprl==0.1.0) (2.5.0)
Requirement already satisfied: opentelemetry-api>=1.9.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-logging->pprl==0.1.0) (1.40.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from opentelemetry-api>=1.9.0->google-cloud-logging->pprl==0.1.0) (8.7.1)
Requirement already satisfied: zipp>=3.20 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.9.0->google-cloud-logging->pprl==0.1.0) (3.23.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-storage->pprl==0.1.0) (2.8.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from google-cloud-storage->pprl==0.1.0) (1.8.0)
Requirement already satisfied: jellyfish>=1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from recordlinkage->pprl==0.1.0) (1.2.1)
Requirement already satisfied: scikit-learn>=1 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from recordlinkage->pprl==0.1.0) (1.8.0)
Requirement already satisfied: joblib in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from recordlinkage->pprl==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/conda/miniconda3/envs/pprl_toolkit/lib/python3.11/site-packages (from scikit-learn>=1->recordlinkage->pprl==0.1.0) (3.6.0)
Building wheels for collected packages: pprl
  Building editable for pprl (pyproject.toml) ... done
  Created wheel for pprl: filename=pprl-0.1.0-0.editable-py3-none-any.whl size=6822 sha256=0a5f4591b55af5ea128f03b31bd2830f61b62e46dadce3d143b022f624ef1e9e
  Stored in directory: /tmp/pip-ephem-wheel-cache-tctg4bfi/wheels/3f/13/a5/bb14a4ee961501247d1c335a95e7ef9692213c776834c0570b
Successfully built pprl
Installing collected packages: pprl
  Attempting uninstall: pprl
    Found existing installation: pprl 0.1.0
    Uninstalling pprl-0.1.0:
      Successfully uninstalled pprl-0.1.0
Successfully installed pprl-0.1.0
Note: you may need to restart the kernel to use updated packages.

## Load Dataset

In [3]:
import pandas as pd

abt = pd.read_csv("data/D2/abtclean.csv", sep='|')
buy = pd.read_csv("data/D2/buyclean.csv", sep='|')

abt.head(10)

,id,name,description,price
0,0,Sony Turntable - PSLX350H,Sony Turntable - PSLX350H/ Belt Drive System/ ...,NaN
1,1,Bose Acoustimass 5 Series III Speaker System -...,Bose Acoustimass 5 Series III Speaker System -...,399.0
2,2,Sony Switcher - SBV40S,Sony Switcher - SBV40S/ Eliminates Disconnecti...,49.0
3,3,Sony 5 Disc CD Player - CDPCE375,Sony 5 Disc CD Player- CDPCE375/ 5 Disc Change...,NaN
4,4,Bose 27028 161 Bookshelf Pair Speakers In Whit...,Bose 161 Bookshelf Speakers In White - 161WH/ ...,158.0
5,5,Denon Stereo Tuner - TU1500RD,Denon Stereo Tuner - TU1500RD/ RDS Radio Data ...,375.0
6,6,KitchenAid Pasta Roller And Cutter - KPRA,KitchenAid Pasta Roller And Cutter - KPRA/ One...,NaN
7,7,Panasonic Yeast Pro Automatic Breadmaker - SDY...,Panasonic Yeast Pro Automatic Breadmaker - SDY...,NaN
8,8,Sony Vertical-In-The-Ear Stereo Headphones - M...,Sony Vertical-In-The-Ear Stereo Headphones - M...,NaN
9,9,Panasonic 2-Line Integrated Telephone - KXTSC14W,Panasonic 2-Line Integrated Telephone - KXTSC1...,NaN

In [4]:
buy.head(10)

,id,name,description,price
0,0,Linksys EtherFast EZXS88W Ethernet Switch - EZ...,Linksys EtherFast 8-Port 10/100 Switch (New/Wo...,NaN
1,1,Linksys EtherFast EZXS55W Ethernet Switch,5 x 10/100Base-TX LAN,NaN
2,2,Netgear ProSafe FS105 Ethernet Switch - FS105NA,NETGEAR FS105 Prosafe 5 Port 10/100 Desktop Sw...,NaN
3,3,Belkin Pro Series High Integrity VGA/SVGA Moni...,1 x HD-15 - 1 x HD-15 - 10ft - Beige,NaN
4,4,Netgear ProSafe JFS516 Ethernet Switch,Netgear ProSafe 16 Port 10/100 Rackmount Switc...,NaN
5,5,LaCie Pocket Floppy Disk Drive - 706018,LaCie Pocket USB Floppy 1.44 MB,NaN
6,6,Canon KP 36IP Print Cartridge / Paper Kit - 77...,36 Page 4' x 6',9.99
7,7,Kensington Orbit Optical Trackball - USB w/PS2...,Optical - USB PS/2,NaN
8,8,Linksys EtherFast EF4116 Ethernet Switch,16 x 10/100Base-TX LAN,NaN
9,9,Linksys EtherFast EF4124 Ethernet Switch,24 x 10/100Base-TX LAN,64.99

## Creating and assigning a feature factory

The next step is to decide how to process each of the columns in our datasets. The pprl.embedder.features module provides functions that process different data types so that they can be embedded into the Bloom filter. We pass these functions into the embedder in a dictionary called a feature factory. We also provide a column specification for each dataset mapping our columns to column types in the factory.

In [5]:
from pprl.embedder import features
from functools import partial


# Map the columns on which we want to generate features to the corresponding feature generation functions
factory = {'name' : features.gen_name_features}
spec_abt = {'name' : 'name'}
spec_buy = {'name' : 'name'}

## Embedding the data

With our specifications sorted out, we can get to creating our Bloom filter embedding. We can create our Embedder instance and use it to embed our data with their column specifications. The Embedder object has two more parameters: the size of the filter and the number of hashes. We can use the defaults.

In [6]:
from pprl.embedder import Embedder

embedder : Embedder = Embedder(factory, bf_size=1024, num_hashes=12)
abt_embedded = embedder.embed(abt, colspec=spec_abt, update_thresholds=True)
buy_embedded = embedder.embed(buy, colspec=spec_buy, update_thresholds=True)

## Performing the linkage

We can now perform the linkage by comparing these Bloom filter embeddings. The package uses the Soft Cosine Measure to calculate record-wise similarity scores.

In [9]:
similarities = embedder.compare(abt_embedded, buy_embedded)

similarities[:10]

SimilarityArray([[0.50735052, 0.50183481, 0.52572983, ..., 0.46103728,
                  0.4766221 , 0.51545246],
                 [0.59968444, 0.59800037, 0.60950366, ..., 0.56317602,
                  0.62043966, 0.66574252],
                 [0.58039038, 0.58353049, 0.57355936, ..., 0.40130631,
                  0.43276806, 0.48136776],
                 ...,
                 [0.593624  , 0.59174905, 0.60563242, ..., 0.56330144,
                  0.59629681, 0.65330582],
                 [0.60723842, 0.6105238 , 0.6400589 , ..., 0.56872047,
                  0.58676706, 0.66284995],
                 [0.61047363, 0.60871791, 0.58898   , ..., 0.56197696,
                  0.60479893, 0.66890357]])

Lastly, we compute the matching using an adapted Hungarian algorithm with local match thresholds:

In [24]:
matching = similarities.match()

print(f"Returns {len(matching)} arrays one for ABT and one for BUY")
print(f"Where each item of ABT is matched with each item of BUY.\nPrinting the shapes of the 2 arrays: {matching[0].shape}, {matching[1].shape}")

Returns 2 arrays one for ABT and one for BUY
Where each item of ABT is matched with each item of BUY.
Printing the shapes of the 2 arrays: (321,), (321,)

## Evaluation

In [32]:
ground_truth = pd.read_csv("data/D2/gtclean.csv", sep='|')

true_positives = 0
total_matching_pairs = matching[0].shape[0]

for _, (id1, id2) in ground_truth.iterrows():
    if id1 in matching[0]:
        id1_indices = (matching[0] == id1).nonzero()
        for id1_index in id1_indices:
            if id2 == matching[1][id1_index]:
                true_positives += 1

num_of_true_duplicates = ground_truth.shape[0]
false_negatives = num_of_true_duplicates - true_positives
false_positives = total_matching_pairs - true_positives
cardinality = abt.shape[0] * buy.shape[0]
true_negatives = cardinality - false_negatives - num_of_true_duplicates
precision = true_positives / total_matching_pairs
recall = true_positives / num_of_true_duplicates
if precision == 0.0 or recall == 0.0:
    f1 = 0.0
else:
    f1 = 2*((precision*recall)/(precision+recall))

print(f"Precision: {precision}\nRecall: {recall}\nF1: {f1}")

Precision: 0.5482866043613707
Recall: 0.16541353383458646
F1: 0.25415162454873647